//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExsitecParonAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int number { get; set; }
        public string productNo { get; set; }
        [Required(ErrorMessage = "Skriv in ett namn på produkten.")]
        public string productName { get; set; }
        [Required(ErrorMessage = "Var god välj pris.")]
        public Nullable<int> price { get; set; }
    }
}
