//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExsitecParonAB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProductTransaction
    {
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dateTransaction { get; set; }
        public string productName { get; set; }
        public string city { get; set; }
        [Required(ErrorMessage = "Var god välj antal produkter.")]
        public int amount { get; set; }
    }
}
